### ISSUE TITLE
Will not build with Packer >0.7.5

### ISSUE THREAD

**Issue by Miserlou** [sorah/packer-builder-amazon-scratch#2]
--> darwin/386 error: exit status 2
Stderr: # github.com/sorah/packer-builder-amazon-scratch/builder/amazon/scratch
../../src/github.com/sorah/packer-builder-amazon-scratch/builder/amazon/scratch/builder.go:29: undefined: packer.ConfigTemplate

Seems Packer API changed >0.7.5 - ex https://github.com/MSOpenTech/packer-azure/issues/72 - please either update to work the latest Packer APIs, or set the tag in the dependency!

(Trying to get PBAS to build right now.. I may have more errors shortly..)

**Comment by Miserlou** [comment]
I think having TBAS build with the latest Packer would be smarter than freezing the dep at 0.7.5, as there are some other significant bugs fixed since then, like this one: https://github.com/mitchellh/packer/commit/dbaf865e59c2a87198c461b79f57f0d6c8165947
